// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyService.Models;

namespace PolicyService.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20201109210830_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyService.Models.DevicePlatform", b =>
                {
                    b.Property<short>("DevicePlatformId")
                        .HasColumnType("smallint");

                    b.Property<string>("DevicePlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("DevicePlatformId");

                    b.ToTable("DevicePlatforms");
                });

            modelBuilder.Entity("PolicyService.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<short>("PlatformId")
                        .HasColumnType("smallint");

                    b.Property<string>("PolicyDefaultParam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyInstruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PolicyId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("PolicyService.Models.Policy", b =>
                {
                    b.HasOne("PolicyService.Models.DevicePlatform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
