// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicySetService.Models;

namespace PolicySetService.Migrations
{
    [DbContext(typeof(PolicySetDbContext))]
    partial class PolicySetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("GroupService.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = new Guid("b96c8d96-94d5-40df-bdc8-852b10199a4a"),
                            GroupName = "Admin"
                        });
                });

            modelBuilder.Entity("LoginService.Models.Login", b =>
                {
                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Certificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            LoginId = new Guid("fa3585fd-b259-4bb5-a37e-ce917fd13154"),
                            Certificate = "BwIAAACkAABSU0EyAAQAAAEAAQAhV7VjfSecV/26TakgrUsnnfaK7T/OuQaVj7uND40sJyr0gG2CfRB0rdhDcnNpNsb8Necz78mAxhiAN4MgrvwB334f4vWGlTOqrCaTSVmh5ubWTcUSVCmG8IrvCRAjDjPWDJj33/tF4CNVwClYD4LvmPG0+/tOQOZUdwIsibEp1eMFXmlPdXyA70YrtHrafJBAQeGPfqOpfh1yoFRu3UebV05vlxsY8ZzWdiR6LxuJ5kYz+Y5ZXzprZfHikEJayNkrXguOuOsu1caBA1kFw/OWhNjYOYvYx3eWpZf+19Zj/wK1FSfmh+30L/EFCcZz0lutRCyRlKyp5+IqsLKazZH6t6BeinsYhP0bt4THnvfyEykdYe75Grf2oTe3uTSkHXBnKD3fDiLgXD5KBgf9x5di8o8D6CDD7vkkH5Eg54PClVlmftda3uL3K4MIl/nmjkgqsYEmspjBnfjQRWWNAn8+nCFuGDAX1xUe517VqWnZQyExNjP6ivXFKYV10K5lZY4J5wmQzl2wk20q4XIhFF3IeVlVpC5Es+V6f2e+rRG1GbdL0b/ETPHkItGcdeF7p1kHQE7JEeEnGcoap2SpBsgCYXLAvKwGXN5lO61rMjoc6gJZ75i8fyRVD2a7O8kDDTm25eZFwAmAwQQxKDhffatXXstjM+dRPMMa0Y6xNXCoecfUWZ/iaEJB0MQWSkYg3rWYfuhWibu3Vx/MP8AWrCmPEJqaLutyuc3tM85ZldqAnsujfLjRfHAHwAXWy8dwnL0=",
                            GroupId = new Guid("b96c8d96-94d5-40df-bdc8-852b10199a4a"),
                            LogIn = "Admin",
                            Password = "827ccb0eea8a706c4c34a16891f84e7b",
                            UserId = new Guid("a1972983-5389-49c5-a64d-bc4a65861a53")
                        });
                });

            modelBuilder.Entity("PolicyService.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("PlatformId")
                        .HasColumnType("smallint");

                    b.Property<string>("PolicyDefaultParam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyInstruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PolicyId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("PolicySetService.Models.PolicySet", b =>
                {
                    b.Property<Guid>("PolicySetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyParam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Selected")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PolicySetId");

                    b.HasIndex("GroupId");

                    b.HasIndex("LoginId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicySets");
                });

            modelBuilder.Entity("PolicySetService.Models.PolicySet", b =>
                {
                    b.HasOne("GroupService.Group", "PolicySetGroup")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("LoginService.Models.Login", "UserLogin")
                        .WithMany()
                        .HasForeignKey("LoginId");

                    b.HasOne("PolicyService.Policy", "PolicySetPolicy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicySetGroup");

                    b.Navigation("PolicySetPolicy");

                    b.Navigation("UserLogin");
                });
#pragma warning restore 612, 618
        }
    }
}
