// <auto-generated />
using System;
using DeviceService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeviceService.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    partial class DeviceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DevicePlatformEntity.DevicePlatform", b =>
                {
                    b.Property<short>("DevicePlatformId")
                        .HasColumnType("smallint");

                    b.Property<string>("DevicePlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("DevicePlatformId");

                    b.ToTable("DevicePlatforms");

                    b.HasData(
                        new
                        {
                            DevicePlatformId = (short)1,
                            DevicePlatformName = "Android"
                        },
                        new
                        {
                            DevicePlatformId = (short)2,
                            DevicePlatformName = "IOS"
                        },
                        new
                        {
                            DevicePlatformId = (short)3,
                            DevicePlatformName = "Windows"
                        },
                        new
                        {
                            DevicePlatformId = (short)4,
                            DevicePlatformName = "Linux"
                        });
                });

            modelBuilder.Entity("DeviceService.Device", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceMacAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("DevicePlatformId")
                        .HasColumnType("smallint");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("DeviceId");

                    b.HasIndex("DevicePlatformId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceService.Device", b =>
                {
                    b.HasOne("DevicePlatformEntity.DevicePlatform", "DevicePlatform")
                        .WithMany()
                        .HasForeignKey("DevicePlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevicePlatform");
                });
#pragma warning restore 612, 618
        }
    }
}
